services:
  elasticsearch:
    build: ./elasticsearch
    platform: linux/arm64  # Macネイティブ（ARM64）で動作
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    networks:
      - search-network

  opensearch:
    build: ./opensearch
    platform: linux/arm64  # Macネイティブ（ARM64）で動作
    container_name: opensearch
    ports:
      - "9201:9200"
    networks:
      - search-network

networks:
  search-network:
    driver: bridge

volumes:
  es-data:
  os-data: